upstream django_app {
    server web:8000;
}

server {
    listen 80;
    # Указываем домены. IP лучше убрать, чтобы не путать Certbot
    server_name foodpetgram.msk.ru www.foodpetgram.msk.ru;

    # === ВАЖНО: Блок для Certbot ===
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    # ================================

    location /static/ {
        alias /app/foodcalc/static_backend/;
        expires 30d;
        access_log off;
    }

    location /media/ {
        alias /app/foodcalc/media/;
    }

    # Пока просто проксируем запросы на Django (без редиректа на HTTPS)
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}