upstream django_app {
    # web - это имя сервиса в docker-compose.yml
    server web:8000;
}

server {
    listen 80;
    server_name foodpetgram.msk.ru www.foodpetgram.msk.ru 185.221.154.36; # Можно заменить на домен, когда будет

    client_max_body_size 100M; # Разрешаем загрузку файлов до 100Мб

    # Статика (CSS, JS, картинки из STATIC_ROOT)
    location /static/ {
        # Путь внутри контейнера Nginx должен совпадать с путем в Volume
        alias /app/foodcalc/static_backend/;
        expires 30d;
        access_log off;
    }

    # Медиа (файлы, загруженные пользователями)
    location /media/ {
        alias /app/foodcalc/media/;
    }

    # Основные запросы -> Gunicorn
    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}