# Generated by Django 5.0.7 on 2024-08-02 03:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название на латинском"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Название на русском"),
                ),
                (
                    "info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Дополнительная информация"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PetStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=50, verbose_name="Описание стадии"),
                ),
                (
                    "pet_stage",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Стадия питомца"
                    ),
                ),
                (
                    "sterilized",
                    models.BooleanField(verbose_name="питомец стерилизован?"),
                ),
                (
                    "nursing",
                    models.BooleanField(verbose_name="Является ли питомец кормящей"),
                ),
                (
                    "age_start",
                    models.IntegerField(
                        help_text="с какого возраста начинается эта стадия",
                        verbose_name="начало стадии",
                    ),
                ),
                (
                    "age_finish",
                    models.IntegerField(
                        help_text="до какого возраста длится эта стадия",
                        verbose_name="конец стадии",
                    ),
                ),
                ("MER_power", models.FloatField()),
                (
                    "pet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animal.animaltype",
                        verbose_name="тип питомца",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя питомца")),
                (
                    "nursing",
                    models.BooleanField(verbose_name="Является ли питомец кормящей"),
                ),
                (
                    "sterilized",
                    models.BooleanField(verbose_name="питомец стерилизован?"),
                ),
                (
                    "weight",
                    models.FloatField(
                        help_text="Масса питомца, в кг",
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Вес",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        help_text="При возрасте более года рацион\n        рассчитывается для взрослых собак",
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хозяин",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type",
                        to="animal.animaltype",
                        verbose_name="Тип питомца",
                    ),
                ),
            ],
            options={
                "unique_together": {("owner_id", "name")},
            },
        ),
    ]
