# Generated by Django 3.2.16 on 2024-07-15 02:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='weight',
            field=models.FloatField(help_text='Масса питомца, в кг', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)], verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='description',
            field=models.TextField(verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название на латинском'),
        ),
    ]
