# Generated by Django 3.2.16 on 2024-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20240715_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstage',
            name='MER_power',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
