# Generated by Django 3.2.16 on 2024-07-16 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animal', '0003_petstage_mer_power'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('owner_id', 'name')},
        ),
    ]
