# Generated by Django 3.2.16 on 2024-07-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_alter_animal_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaltype',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Название на русском'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название на латинском'),
        ),
        migrations.AlterField(
            model_name='petstage',
            name='pet_stage',
            field=models.CharField(max_length=50, unique=True, verbose_name='Стадия питомца'),
        ),
    ]
