# Generated by Django 3.2.16 on 2024-07-12 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, unique=True, verbose_name='Название продукта')),
                ('ndbNumber', models.IntegerField()),
                ('fdcId', models.IntegerField()),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить продукт.', verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='NutrientsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=10)),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить нутриент.', verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NutrientsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='food.food', verbose_name='Продукт')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='food.nutrientsname', verbose_name='Имя нутриента')),
            ],
        ),
    ]
