# Generated by Django 5.0.7 on 2024-08-02 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NutrientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Название продукта"
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=300, null=True)),
                ("ndbNumber", models.IntegerField()),
                ("fdcId", models.IntegerField()),
                ("foodCategory", models.CharField(default="None", max_length=150)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы не выводить продукт.",
                        verbose_name="Опубликовано",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Составитель нутриентов продукта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="NutrientsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "short_name",
                    models.CharField(
                        default=models.CharField(max_length=50), max_length=10
                    ),
                ),
                ("unit_name", models.CharField(max_length=10)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Снимите галочку, чтобы не выводить нутриент.",
                        verbose_name="Опубликовано",
                    ),
                ),
                ("order", models.IntegerField(default=100)),
                (
                    "nutr_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="group_name",
                        to="food.nutrientgroup",
                        verbose_name="Группа нутриентов",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NutrientsQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Количество")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quan",
                        to="food.food",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quan",
                        to="food.nutrientsname",
                        verbose_name="Имя нутриента",
                    ),
                ),
            ],
            options={
                "unique_together": {("food", "nutrient")},
            },
        ),
    ]
