# Generated by Django 5.0.7 on 2024-08-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrientsname",
            name="short_name",
            field=models.CharField(default="food.NutrientsName.name",
                                   max_length=10),
        ),
    ]
