# Generated by Django 3.2.16 on 2024-07-15 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Составитель нутриентов продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='foodCategory',
            field=models.CharField(default='None', max_length=150),
        ),
    ]
