# Generated by Django 3.2.16 on 2024-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20240715_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
