# Generated by Django 5.0.7 on 2024-08-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_alter_nutrientsname_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrientsname",
            name="short_name",
            field=models.CharField(
                default=models.CharField(max_length=50), max_length=10
            ),
        ),
    ]
