# Generated by Django 3.2.16 on 2024-07-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
