# Generated by Django 5.0.7 on 2024-07-20 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_alter_food_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="nutrientsquantity",
            unique_together={("food", "nutrient")},
        ),
    ]
