# Generated by Django 5.0.7 on 2024-08-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0004_alter_nutrientsname_short_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nutrientsname",
            name="short_name",
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
