# Generated by Django 5.0.7 on 2024-08-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0005_alter_nutrientsname_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nutrientgroup",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="nutrientgroup",
            name="order",
            field=models.IntegerField(default=100),
        ),
    ]
