# Generated by Django 5.0.7 on 2024-08-02 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0006_alter_nutrientgroup_options_nutrientgroup_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nutrientgroup",
            old_name="group",
            new_name="name",
        ),
    ]
