# Generated by Django 3.2.16 on 2024-06-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ndbNumber', models.IntegerField()),
                ('fdcId', models.IntegerField()),
                ('foodCategory', models.CharField(max_length=50)),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить продукт.', verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=10)),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить нутриент.', verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='calc.food', verbose_name='Продукт')),
                ('nutrient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='calc.nutrientsname', verbose_name='Имя нутриента')),
            ],
        ),
    ]
