# Generated by Django 3.2.16 on 2024-07-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('ndbNumber', models.IntegerField()),
                ('fdcId', models.IntegerField()),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить продукт.', verbose_name='Опубликовано')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit_name', models.CharField(max_length=10)),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы не выводить нутриент.', verbose_name='Опубликовано')),
                ('order', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='PetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Описание стадии')),
                ('pet_stage', models.CharField(max_length=50, verbose_name='Стадия питомца')),
                ('sterilized', models.BooleanField(verbose_name='питомец стерилизован?')),
                ('nursing', models.BooleanField(verbose_name='Является ли питомец кормящей')),
                ('age_start', models.IntegerField(help_text='с какого возраста начинается эта стадия', verbose_name='начало стадии')),
                ('age_finish', models.IntegerField(help_text='до какого возраста длится эта стадия', verbose_name='конец стадии')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.animaltype', verbose_name='тип питомца')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedNutrientLevelsDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_amount', models.FloatField(verbose_name='Количество')),
                ('nutrient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_info', to='calc.nutrientsname', verbose_name='Нутриент')),
                ('pet_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.petstage')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.animaltype', verbose_name='тип питомца')),
            ],
        ),
        migrations.CreateModel(
            name='Rations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50, verbose_name='Имя питомца')),
                ('ration_name', models.CharField(max_length=50, verbose_name='Название рациона')),
                ('ration_comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Составитель рациона')),
                ('pet_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.petstage')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='calc.food', verbose_name='Продукт')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quan', to='calc.nutrientsname', verbose_name='Имя нутриента')),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='calc.food')),
                ('ration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ration', to='calc.rations')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя питомца')),
                ('nursing', models.BooleanField(verbose_name='Является ли питомец кормящей')),
                ('sterilized', models.BooleanField(verbose_name='питомец стерилизован?')),
                ('weight', models.FloatField(help_text='Масса питомца, в кг', verbose_name='Вес')),
                ('birthday', models.DateField(help_text='При возрасте более года достаточно указать год', verbose_name='Дата рождения')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Хозяин')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='calc.animaltype', verbose_name='Тип питомца')),
            ],
        ),
    ]
