# Generated by Django 3.2.16 on 2024-07-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='animaltype',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Rations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50, verbose_name='Имя питомца')),
                ('pet_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.petstage')),
            ],
        ),
        migrations.CreateModel(
            name='FoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='calc.food')),
                ('ration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ration', to='calc.rations')),
            ],
        ),
    ]
