# Generated by Django 3.2.16 on 2024-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientsname',
            name='order',
            field=models.IntegerField(default=100),
        ),
    ]
