# Generated by Django 3.2.16 on 2024-07-04 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooddata',
            old_name='ration_id',
            new_name='ration',
        ),
    ]
