# Generated by Django 3.2.16 on 2024-07-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendednutrientlevelsdm',
            old_name='amount',
            new_name='nutrient_amount',
        ),
        migrations.RemoveField(
            model_name='recommendednutrientlevelsdm',
            name='nutrient',
        ),
        migrations.AddField(
            model_name='recommendednutrientlevelsdm',
            name='nutrient_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nutrient_info', to='calc.nutrientsname', verbose_name='Нутриент'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PetStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_stage', models.CharField(max_length=50, verbose_name='Стадия питомца')),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.animaltype', verbose_name='тип питомца')),
            ],
        ),
        migrations.AlterField(
            model_name='recommendednutrientlevelsdm',
            name='pet_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.petstage'),
        ),
    ]
