# Generated by Django 5.0.7 on 2024-07-18 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calc", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rations",
            name="pet_weight",
            field=models.FloatField(default=4.2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="rations",
            unique_together={("owner", "ration_name")},
        ),
    ]
