# Generated by Django 3.2.16 on 2024-07-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_rename_ration_id_fooddata_ration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='birthday',
            field=models.DateField(help_text='При возрасте более года рацион\n        рассчитывается для взрослых собак', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
