# Generated by Django 3.2.16 on 2024-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20240701_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sterilized',
            field=models.BooleanField(default=0, verbose_name='питомец стерилизован?'),
            preserve_default=False,
        ),
    ]
