# Generated by Django 3.2.16 on 2024-07-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20240704_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='rations',
            name='ration_comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AddField(
            model_name='rations',
            name='ration_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Название рациона'),
            preserve_default=False,
        ),
    ]
