# Generated by Django 3.2.16 on 2024-07-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_animal_sterilized'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstage',
            name='age_finish',
            field=models.IntegerField(default=9999, help_text='до какого возраста длится эта стадия', verbose_name='конец стадии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petstage',
            name='age_start',
            field=models.IntegerField(default=0, help_text='с какого возраста начинается эта стадия', verbose_name='начало стадии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petstage',
            name='nursing',
            field=models.BooleanField(default=0, verbose_name='Является ли питомец кормящей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petstage',
            name='sterilized',
            field=models.BooleanField(default=0, verbose_name='питомец стерилизован?'),
            preserve_default=False,
        ),
    ]
