# Generated by Django 3.2.16 on 2024-07-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_auto_20240711_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='nutrientsname',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='fooddata',
            name='weight',
            field=models.FloatField(),
        ),
    ]
