# Generated by Django 3.2.16 on 2024-06-28 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calc', '0004_auto_20240628_0649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animals',
            new_name='Animal',
        ),
        migrations.RenameModel(
            old_name='AnimalTypes',
            new_name='AnimalType',
        ),
    ]
