# Generated by Django 3.2.16 on 2024-06-28 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_auto_20240628_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='mass',
        ),
        migrations.AddField(
            model_name='animal',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, help_text='При возрасте более года достаточно указать год', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='nursing',
            field=models.BooleanField(default=1, verbose_name='Является ли питомец кормящей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.FloatField(default=0, help_text='Масса питомца, в кг', verbose_name='Вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя питомца'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='calc.animaltype', verbose_name='Тип питомца'),
            preserve_default=False,
        ),
    ]
