# Generated by Django 3.2.16 on 2024-06-30 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_auto_20240628_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedNutrienLevelsDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=50, verbose_name='Тип питомца')),
                ('pet_stage', models.CharField(max_length=50, verbose_name='Стадия питомца')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrient', to='calc.nutrientsname', verbose_name='Нутриент')),
            ],
        ),
    ]
