# Generated by Django 3.2.16 on 2024-06-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_recommendednutrienlevelsdm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedNutrienLevelsDM',
            new_name='RecommendedNutrientLevelsDM',
        ),
    ]
